### ISSUE TITLE
Share JLab 3.0 in community calls

### ISSUE THREAD

**Issue by isabela-pf** [jupyterlab/team-compass#115]
Hi all!

I’m hosting the upcoming Jupyter community calls on January 26 and February 23 at 9am Pacific. As always, anyone is welcome to share something they are working on or with from anywhere in the Jupyter ecosystem. But with the recent release of 3.0, I thought this might be a good opportunity to show of all that’s new in this major release.

Is anyone interested in sharing their favorite things new to 3.0 in one of the next calls?

If you want to share something (3.0 or otherwise), please sign up in the [agenda](https://hackmd.io/l2yBruUATC6yH4F2gOUPgw) before the call begins and join us on [Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09) the day of. Feel free to ask me here or visit the [Discourse post](https://discourse.jupyter.org/t/jupyter-community-calls/668) if you have questions about community calls.

Thanks in advance, and hope to see you soon!

**Comment by isabela-pf** [comment]
We had a few demos that mentioned JupyterLab 3.0 at the January community call today, but I'm going to leave this issue open for next month since I still think it will be new to lots of people!

Sign up for the February call here on the [agenda](https://hackmd.io/WZ9DCwZrQummM89-k3bC0A).

The January call recording can be found on [youtube](https://youtu.be/DS_J3mzulCw).

**Comment by isabela-pf** [comment]
February's community call is in two weeks (on Feburary 23 at 9am Pacific, or [your timezone](https://arewemeetingyet.com/Los%20Angeles/2021-02-23/9:00/Jupyter%20Community%20Call)). I still think it would be great to hear about JupyterLab 3 so I'm on this issue again!

If you want to share about this (or anything else Jupyter-related), please sign up before the call on the [agenda](https://hackmd.io/WZ9DCwZrQummM89-k3bC0A). You can always find more info on the [Discourse post](https://discourse.jupyter.org/t/jupyter-community-calls/668). Hope to see you in two weeks!

**Comment by isabela-pf** [comment]
We had another lovely community call, so I'm closing this issue. I may promote other prompts for presentations in the future. 

Thanks to the community for all your support, and all content from the last call is linked on [Discourse](https://discourse.jupyter.org/t/jupyter-community-calls/668)!

**Comment by choldgraf** [comment]
Thanks @isabela-pf for being on top of all of this, and for wrangling the issues and calls a bit, it is super super appreciated 🙏
