### ISSUE TITLE
January 20th - Cancel Team Meeting?

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#116]
Given that the Presidential Inauguration is scheduled to take place during the regularly scheduled meeting, should we plan to cancel this week's meeting and pick up next week?

**Comment by jasongrout** [comment]
I'm okay with still having a meeting. I think it makes sense to introduce the 4.0 planning spreadsheet soon (if not tomorrow, maybe asynchronously this week) so we can start thinking and planning a roadmap.

**Comment by jasongrout** [comment]
I'm also okay with canceling the meeting if most people won't be there.

**Comment by afshin** [comment]
I will log into the meeting even if the news is on in the background. I think it's important to at least get people thinking about the spreadsheet, too.

I don't think most people will be absent, but that's just a hunch.

**Comment by jasongrout** [comment]
I will log in too, and we can make a decision when we see who is there.
