### ISSUE TITLE
Community Health File Proposal

### ISSUE THREAD

**Issue by afshin** [jupyterlab/team-compass#123]
### Background
JupyterHub has implemented a community health [repo](https://github.com/jupyterhub/.github) that provides the following across the org:

- Default Code of Conduct
- Bug report and feature request issue templates
- Contact link pointing to Jupyter Discourse 
- Welcome bot for new issues and first merged PRs with fantastic Jupyter-specific images made by @GeorgianaElena

<image src="https://raw.githubusercontent.com/jupyterhub/.github/master/images/welcome.jpg" height=200px></image>
<image src="https://raw.githubusercontent.com/jupyterhub/.github/master/images/congrats.jpg" height=200px></image>

- Request info bot to ask for more information on an issue

Notes from the [docs](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file):

```
For example, anyone who creates an issue or pull request in a public repository that does not have its own CONTRIBUTING file 
will see a link to the default CONTRIBUTING file. If a repository has any files in its own .github/ISSUE_TEMPLATE folder, 
including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

Default files are not included in clones, packages, or downloads of individual repositories because they are stored only in 
the .github repository.
```

## Proposal

- Adopt the JupyterHub .github org, tweaking slightly for anything org-specific
- Add a `SECURITY.md` pointing to our [security docs](https://jupyter-server.readthedocs.io/en/latest/operators/security.html)
- Add a `SUPPORT.md` pointing folks to Discourse for help

**Comment by blink1073** [comment]
Initial population [done](https://github.com/jupyterlab/.github/tree/a39a7812c074ae7482c93b69dbc53cfa4e2bb39d).
