### ISSUE TITLE
“What should I work on?” – JupyterLab 4.0 feature-pairing meeting

### ISSUE THREAD

**Issue by afshin** [jupyterlab/team-compass#124]
After discussing the [feature ideas for JupyterLab 4.0](https://docs.google.com/spreadsheets/d/1r6_ySd18xZwfPexdmlkdFhHUWynaza0zXjrxMMIoLWw/edit#gid=0), we have many issues that are compelling but do not have individual contributors who have been able to commit to working on them.

Let's have a call where people who are interested in working on JupyterLab 4.0 and have some cycles to spare can become acquainted with the outstanding items on the list and sign up to work on them.

**Comment by afshin** [comment]
Please add your availability here!

http://whenisgood.net/ih3wh7r

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/i-want-to-work-on-jupyterlab-4-0-what-should-i-work-on/8871/1

**Comment by jtpio** [comment]
At the JupyterLab weekly meeting yesterday, we decided to postpone this call to next week: https://github.com/jupyterlab/team-compass/issues/117#issuecomment-833277856

**Comment by afshin** [comment]
I think it's time.
