### ISSUE TITLE
Proposal: Maintainer Tools Repo

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#131]
As discussed at this week's dev [meeting](https://github.com/jupyterlab/team-compass/issues/128#issuecomment-947858309), this proposal is to create a new repo, notionally called `maintainer-tools`.

The goal of the repo is to have actions and workflows that are useful for maintainers, such as:

 - Workflow to run a script against a PR as a [maintainer](https://github.com/jupyterlab/jupyterlab/pull/11318/commits/1b46eef88b0e9d3ab7d401e0c5f6c179170d8508) (relevant code will be open sourced once this repo is created).  The workflow is meant to be run from a fork using the maintainer's own GitHub credentials.
 - Common GitHub [actions](https://github.com/jupyter-server/jupyter_releaser/pull/182) that can be used in other repos, using the new [action composition](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/) capability in GitHub Actions

This repo could also be used by sibling GitHub orgs like `jupyter-server`, or they could decide to adopt this pattern and have their own `maintainer-tools` if the workflows/actions needed to diverge.

**Comment by blink1073** [comment]
Step 1: https://github.com/jupyterlab/maintainer-tools/pull/1

**Comment by jtpio** [comment]
The maintainer tools repo now has a couple of actions used across several repos.

Looks like we could then close this issue?

**Comment by blink1073** [comment]
Yep!
