### ISSUE TITLE
transfer classic jupyter/notebook to the jupyterlab organization

### ISSUE THREAD

**Issue by tonyfast** [jupyterlab/team-compass#132]
as we manage the transition to notebook 7, we'll need to move issues between the repos. [projects need to be in the same organization to transfer issues between projects][transfer]. would it be possible to move classic to jupyterlab organization to prepare for notebook 7.0? are there any major downfalls of this choice?

there are some drafts issues on the [sunrise project board](https://github.com/orgs/jupyterlab/projects/2) that will be hampered by the separate organizations, and recently this became a concern when merging retrolab issues in notebook classic https://github.com/jupyter/notebook/issues/6225#issuecomment-965646801 .

[transfer]: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

cc: @Zsailer @jtpio

**Comment by jtpio** [comment]
Should this be closed now that the general consensus seems to be moving the retrolab code base to the existing `jupyter/notebook` repo? https://github.com/jupyterlab/team-compass/issues/133#issuecomment-1016703643

**Comment by vidartf** [comment]
Closing proactively (aka please have a low threshold for reopening if this is still needed/useful). 😃
