### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/team-compass#136]
At the JupyterLab Meeting Team, a discussion about 3.3 release raised the point of a need to document what are the boundaries for alpha, beta and rc stage (for major and minor versions). And also document how a release calendar is established.

Some suggestions by @jasongrout  on time period during the JLab meeting:

> I think a minimum 1-week RC for 3.3 is reasonable 
> I think a minimum 2-week RC for a major release is reasonable

**Comment by echarles** [comment]
Aside that release process documentation, it would be great to have a link to a published release timeline so users can plan accordingly their deployments.

**Comment by jasongrout** [comment]
Some other thoughts from the meeting were:

1. alpha releases have a fairly low bar - basically that JupyterLab can be installed and run. Bugs are okay, and breaking changes are okay.
2. beta releases have typically tried to not have breaking changes in the api, though I don't think we've followed that guideline particularly faithfully.
3. RC releases have been a signal to the extension developer community that they should start migrating to the new version to test it, and that we basically consider the software stable. We've often put off final release documentation changes or minor UX tweaks to the RC stage. During the RC phase, we also start migrating the extensions we maintain over to the new version to test it. In my experience, this work during the RC phase (and giving time for feedback from extension developers) takes a couple of weeks.

**Comment by jtpio** [comment]
For reference the JupyterLab release process is documented here: https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md

Maybe there could be a new section to explain what the expectations are in terms of the release cycles, as mentioned above. 

Also this is really for JupyterLab only, as the other repos in the `jupyterlab` org have a lower bar and enforcing this process would add too much friction.

**Comment by jtpio** [comment]
Also since JupyterLab releases are now easier to make with the Jupyter Releaser, we can more easily distribute the release management process between several people, so there is not only one person entitled to do it (to avoid bottlenecks).

**Comment by jtpio** [comment]
I just opened https://github.com/jupyterlab/jupyterlab/pull/12074 as a draft PR to start documenting the release process in the JupyterLab repo,
