### ISSUE TITLE
Use of pre-commit

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#142]
## Description
I added the https://pre-commit.ci/ GitHub App to the org.  By default this means that any repo with a `.pre-commit-config.yaml` file will get a weekly PR to update the versions used.  This will help us keep them up to date easier.

cf https://github.com/jupyterlab/jupyterlab/issues/12272

**Comment by fcollonval** [comment]
This turns CI to red when pre-commit is not configured for example for `jupyterlab/pull-request`: https://results.pre-commit.ci/run/github/198751265/1648550407.f6iK8ik0SG-Ao664S91hLg

Would it be possible to turn it on only on `jupyterlab`? and maybe on `jupyterlab_server`?

> I'll raise the question at weekly call.

**Comment by blink1073** [comment]
Oh bummer, I thought it would just not run if the file wasn't there.  Sure, I'll update to scope it to those two repos.

**Comment by blink1073** [comment]
Done!

**Comment by blink1073** [comment]
For those with access, the settings are at: https://github.com/organizations/jupyterlab/settings/installations/24508674

**Comment by jtpio** [comment]
Is there a way to re-run the checks?

Looks like it fails on the latest commit:

- https://github.com/jupyterlab/jupyterlab/commit/fa7578e39b24741e2a5eb2ebd7cc50fbb3a02424
- https://results.pre-commit.ci/run/github/60374819/1648556934.JUoSwSjVQq-DJygt-mo0nw

Not sure if it's a real failure or just need to be kicked.

**Comment by blink1073** [comment]
It seems like the `jsonschema` download can't work on the service, we probably need to [skip it](https://pre-commit.ci/#configuration-skip).

**Comment by blink1073** [comment]
cf https://github.com/jupyter-server/jupyter_server/pull/766

**Comment by blink1073** [comment]
I removed it from JupyterLab as well, because we don't have access to `pypi` or `npm` to download the files needed to run the local hooks.

What could be done instead is to use the official mirrors for [prettier](https://github.com/pre-commit/mirrors-prettier) and [eslint](https://github.com/pre-commit/mirrors-eslint).  Since there is isn't an official mirror for `stylelint`, that could be run in GitHub actions only.  So the skip config would look like:

```
ci:
  skip: [check-jsonschema, stylelint, eslint]
```

That would involve trying to de-conflict what is currently part of the top level `package.json` including dependencies.  I think what would happen is that the versions of the plugins would need to be included in the eslint config, and a separate job for `eslint:check:typed` would need to be run as a manual hook, which wouldn't run on pre-commit.ci either.  So this all seems like a lot of work for the autoupdate feature...

**Comment by blink1073** [comment]
Ha, another, less-hacky idea is to skip all of the local checks on `pre-commit.ci`.

**Comment by fcollonval** [comment]
@blink1073 could we consider this as resolved?

**Comment by blink1073** [comment]
Sounds good
