### ISSUE TITLE
Please help release Lumino 2

### ISSUE THREAD

**Issue by afshin** [jupyterlab/team-compass#158]
## Context

I mistakenly imagined that getting from Lumino 1 to Lumino 2 would be pretty easy. I planned to do it myself over the span of a couple days. It turns out I was mistaken, Lumino 2 is a nontrivial update even if the API changes themselves are modest.

Over the past week or two, we have been tackling some of the issues to get us closer to a release &mdash; because JupyterLab 4 is the proximate best opportunity to shed some old code, modernize, optimize, and ship Lumino 2. Otherwise we would have to wait until JupyterLab 5.

## Request

I am writing to invite you to work on this or ask someone you know to work on it in all of the various ways work on it can be interpreted.

## Details

To facilitate this work, we have a [project board of issues](https://github.com/orgs/jupyterlab/projects/4/views/1) and prioritized them intentionally but without thinking too hard about it. Feel free to take on any unclaimed issue even if it is not the top one. Also, feel free to bring pre-existing issues or new issues into the [Lumino 2 milestone](https://github.com/jupyterlab/lumino/milestone/1) and onto the [Lumino 2 project board](https://github.com/orgs/jupyterlab/projects/4/views/1).

I think one of the harder issues is going to be [fixing the performance issues of hit testing in menus](https://github.com/jupyterlab/lumino/issues/329). I'm not 100% sure about this because @krassowski has already done a lot of good investigatory work, so it may be easier than I am imagining.

## The 🐘 in the room
- Lumino 2 will require a lot of code changes in JupyterLab &mdash; they will mostly be mechanical updates and reasonably straightforward to implement. One good way to accomplish this is to potentially create *one* pull request where multiple people push to the same branch and agree on how to split up the work on a package-by-package level. But there are likely other ways to address this as well.
- When I asked @jasongrout, his intuition was that Jupyter Widgets will not require a ton of work, but that it still needs investigating.

---
Relevant upcoming releases: `JupyterLab 4`, `Notebook 7`, `Lumino 2`, `Jupyter Widgets ?`
cf. https://github.com/orgs/jupyterlab/projects/4/views/1

**Comment by afshin** [comment]
cc: @jupyterlab/jupyterlab-council

**Comment by 3coins** [comment]
@afshin I will take a look this week and see where I can help. Thanks.

**Comment by jtpio** [comment]
Closing as Lumino 2 has been released: https://lumino.readthedocs.io/en/latest/changelog.html#id8
