### ISSUE TITLE
Use Releaser Bot on Lumino and JupyterLab Repos

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#165]
Adding releaser bot to a repo makes it easier for contributors with admin access to make releases without the complicated setup of forking `jupyter_releaser` and managing credentials.

We have successfully been using the JuptyerLab releaser bot on `jupyterlab_server`.
We are also using bot releases in on projects in other orgs: `ipython/ipykernel`, `jupyter-server/jupyter_server`, and `nbconvert`.
We have used it with `npm`-publishing projects as well: `jupyter-server/jupyter-scheduler` and `jupyter-server/jupyter-resource_usage`.

See https://github.com/ipython/ipykernel/pull/1020 for an example transition.

I propose we use it to make JupyterLab and Lumino releases, using https://jupyter-releaser.readthedocs.io/en/latest/get_started/making_release_from_repo.html as the release guide.
This would entail giving the bot account admin access to the two repos, and adding appropriate scoped tokens and credentials.

Note that running the workflows triggers a GitHub API check to ensure that the user that triggered the workflow has admin access on the repository.

**Comment by jtpio** [comment]
Sounds good :+1: Especially if it can help keep the workflows the same across repos.

> This would entail giving the bot account admin access to the two repos, and adding appropriate scoped tokens and credentials.

How is the bot account managed? Would it make sense to give access to that bot account to a couple of people here, in case there is a need to rotate tokens for example?

**Comment by blink1073** [comment]
We have a shared password vault for Jupyter.  Several members of the JupyterLab council have access.

**Comment by fcollonval** [comment]
:+1: from me

**Comment by jtpio** [comment]
FYI I opened https://github.com/jupyterlab/jupyterlab/pull/14176 to add the releaser workflows to the repo.

I don't have access to the [jupyterlab-bot](https://github.com/jupyterlab-bot) account to add the missing tokens though. So if someone with access to the shared vault could double check the setup that would be great, thanks!
