### ISSUE TITLE
JupyterCon 2023

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/team-compass#166]
JupyterCon 2023 has been announced and will be held May 10–12 in Paris, France :tada: 

Announcement post on the Jupyter blog: https://blog.jupyter.org/jupytercon-is-back-in-2023-90e5c25eeec9

Opening this issue early to check if folks would be interested in submitted a talk, poster or tutorial for the conference. Some ideas:

- Developing extensions for JupyterLab and Notebook 7
- What's new in JupyterLab 4

The deadline for the CfP is currently set to **December, 15th, 2022 (Anywhere on Earth)**.

Feel free to comment here if you would to submit something, thanks!

### Links

- Website: https://www.jupytercon.com/
- Call for Proposals: https://cfp.jupytercon.com/2023/cfp

**Comment by fcollonval** [comment]
I can propose a tutorial for developing extensions. Is anybody interested to join?

**Comment by krassowski** [comment]
> Happy to join and help with the Notebook 7 / JupyterLite parts if we decide to include them.

It would be great if we can get the plugin-playground on Lite with extra UI bits ready by then. I would be happy to join to plug it.

**Comment by fcollonval** [comment]
It seems CfP for tutorial is not yet opened.

**Comment by jtpio** [comment]
cc @echarles for awareness.

We created this issue in the JupyterLab team compass to sync on proposals. We could create another one in the Notebook team compass if you want too so it's more specific to Notebook. But probably it makes sense to keep the discussion here to centralize updates on the 2 subprojects.

**Comment by jtpio** [comment]
> It seems CfP for tutorial is not yet opened.

For reference the page to submit a proposal mentions the following at the moment:

> Tutorial submissions: JupyterCon will offer tutorials, but the CFP for tutorial will open at a later date.

![image](https://user-images.githubusercontent.com/591645/207383243-976a5318-7831-479a-8cee-5ead0e50390c.png)

**Comment by krassowski** [comment]
Was there any update on the tutorials CFP, did I miss it? CC @SylvainCorlay?

**Comment by marthacryan** [comment]
Just saw this and wanted to say I'd also like to join on the tutorial for developing extensions!

**Comment by Carreau** [comment]
Hi, Yes there will be tutorial in parallel of the main conference (Wed/Thu), at not extra price. You will  just need to register as the rooms are quite small (35-40). We'll have:
 - Dask, 
 - Intro to Python
 - Nbdev and quarto.
 - Sklearn.
There will be sprint on Sat and Sun. 

We did not open the CFT for tutorial as the room situation was unclear until quite late (and is still not super clear), and some other complexity. We hope to do better next year, in particular WRT doing it just before the conference and in a better space.
