### ISSUE TITLE
Create a UX research repo for jupyterlab

### ISSUE THREAD

**Issue by GabrielaVives** [jupyterlab/team-compass#168]
### Problem
There is no repository to document user research insights: documentation about all the personas as we discover them, testing methodologies, study analysis, the different ways of conducting research plans, legal documents, information about biases, how to use a design system, etc...

There is a repo in Jupyter called Surveys, but 
- it is only to post study _results_ , here I would like a place to store everything user related
- it is in the Jupyter project, not Jupyterlab. The 2 projects are very different from a user perspective, user research for jupyterlab could be very different from the notebook for example, as they have different use cases.

There is a repo in Jupyterlab called Design, but
- it is for design assets, here I would like to store only research methodologies and insights, to enable people to conduct research themselves or quickly find information about our users

### Proposed Solution
**Create a new repo in JupyterLab for User research**. It would be the place to document insights as we go about:
- personas
- user journeys
- user issues and needs
- testing methodologies, a guide to understand what to use when
- how to create a study protocol
- study reports 
- actionable results

**Comment by ellisonbg** [comment]
Thanks Gabriela, I think this is a good idea. Let's wait to see if others have any input.

**Comment by GabrielaVives** [comment]
We discussed it during the last JupyterLab meeting, and decided not to create a _new repo_ but to _rename_ the existing `Design` repository `UX Research`, as it already has a bit on content that is all research oriented and not design oriented.
