### ISSUE TITLE
Process for triage of JupyterLab 4.0 issues

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/team-compass#178]
During today's meeting we started bumping milestones of issues assigned to 4.0. As quite a lot of time was spent discussing the process I propose we formalise it so that we can move more efficiently next time.

1. A person leading the triage shares the screen and sorts the issues in 4.0 milestone oldest first; restricting to (depending on how far along we are):
    - unassigned (until we exhausted those)
    - assigned but without PR linked
    - anything remaining
2. We move issues to another milestone unless someone volunteers to pick it up earlier:
   - feature requests that are not critical for Notebook 7 to "Future" (or "4.1" if someone volunteers)
   - Notebook 7 features parity issues to "4.1" milestone
   - minor bugs which are not regressions to "4.1" milestone (unless someone volunteers, then they get assigned and the issue stays in "4.0")
   - regressions, major bugs, and issues critical for Notebook 7 stay in "4.0" (and someone has to pick them up)
3. If no one volunteers to work on an issue during the call, we list it in the notes so that members who cannot attend have a chance to claim it.
4. We aim to make a decision in under a minute, with a hard limit of 2:30 minutes. If a discussion starts we try to encourage moving it offline (e.g. by assigning one of the persons leading the discussion), also because it is usually worth writing these thoughts down. The point of the triage is to reach a consensus on whether the issue is a blocker for Lab 4.0 or Notebook 7.0 (i.e. to which milestone we should assign it, per point 2) and not to discuss technical details behind it.

The suggested point (3) is different from what @jasongrout proposed (a transient "4.1-if-no-one-picks-me" milestone).

Please leave :+1: or :-1: if you think this is the process we should follow. For small adjustments to the process as proposed feel free to edit this comment. If you believe a very different process should be used please describe it in a new comment.

**Comment by andrii-i** [comment]
I think proposed process is a way forward as we need to reduce the scope of 4.0.0 and it's hard to reach consensus on closing some of 4.0.0 issues.

**Comment by dlqqq** [comment]
How will this process be implemented? I'm assuming for the next 3-4 weekly JL meetings, we will spend the last 30 minutes (9:30--10:00 PT) triaging issues.

**Comment by krassowski** [comment]
Yes, this is the approach we used for previous releases and started using today too. It might be less or more than 30 minutes depending on what else is on the agenda, but given the number of issues we should aim for longer and keep to time on the agenda items.

**Comment by JasonWeill** [comment]
Earlier this afternoon (PST), I moved all [unassigned open 4.0.0 issues](https://github.com/jupyter/notebook/issues?q=is%3Aissue+is%3Aopen+milestone%3A%224.0.0%22+no%3Aassignee) to the 4.1.0 milestone. If a person wants to complete the work on one of these issues by the expected 4.0.0 release time, they should assign themselves and move the issue from 4.1.0 to 4.0.0 (or ask a person with permissions to do so).

**Comment by krassowski** [comment]
Closing, as apparently another approach was chosen https://github.com/jupyterlab/jupyterlab/issues/9647#issuecomment-1412741852

**Comment by jtpio** [comment]
> I moved all [unassigned open 4.0.0 issues](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+milestone%3A%224.0.0%22+no%3Aassignee) to the 4.1.0 milestone.

Is there a way to get the list of issues that have been moved to 4.1.0? Just so folks have a chance to double check if some of them would require breaking or other major changes.

**Comment by krassowski** [comment]
> Is there a way to get the list of issues that have been moved to 4.1.0?

As far as I know there is not (both I and @fcollonval were moving bugs and maintenance-related issues back to 4.0 afterwards), but you can see what remains in 4.1.0 here:
https://github.com/jupyterlab/jupyterlab/milestone/72
