### ISSUE TITLE
JupyterLab repo write access request

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/team-compass#188]
During the past 3-4 months I've been actively contributing to JupyterLab codebase and participating in PR review process. At this point I feel confident in my understanding of the codebase and PR review process and would like to request write access. This would increase speed and number of PRs being reviewed which would be especially useful with upcoming 4.0.0 release and bug bashing work that would follow it.

**Comment by echarles** [comment]
+1

**Comment by jtpio** [comment]
Closing as Andrii is now part of the JupyterLab Council: https://github.com/jupyterlab/team-compass/pull/189

Welcome and thanks for your work!

**Comment by andrii-i** [comment]
Thank you @jtpio, everyone!
