### ISSUE TITLE
Seeking Participants and In-Person Co-Leaders for JupyterLab 4.0.0 Bug Fixing Sprint at JupyterCon

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/team-compass#191]
I'm proposing a JupyterCon Sprint for a JupyterLab 4.0.0 bug fixing session. As I can only participate remotely, I'm seeking participants and in-person leaders for the sprint. During the sprint, experienced contributors will group up with newcomers and guide them through the process of resolving issues. 

Proposal was submitted on May 1. Please comment with suggestions or if you're interested in leading in-person. 

## Proposal

* Sprint name or theme: JupyterLab 4.0.0 bug fixing session
* Minimum level of expertise needed: Beginner
* Is familiarity with package required? No
* Github repository link: https://github.com/jupyterlab/jupyterlab
* Contributor guidelines link: https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html
* Description of the goal(s) of the sprint, tasks planned an why it is important: This sprint focuses on resolving  [JupyterLab bugs](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+label%3Abug) to ensure stable and seamless user experience in JupyterLab 4.0.0. During the sprint, experienced contributors will group up with newcomers and guide them through the process of resolving issues.

**Comment by fcollonval** [comment]
I'll be happy to join the sprint - unfortunately I may have to leave early in the week-end. So if someone else could volunteer to lead that will be great.

**Comment by andrii-i** [comment]
The sprint won't happen as there are no in-person hosts

**Comment by fcollonval** [comment]
Thanks @andrii-i for the follow-up.
