### ISSUE TITLE
Project update by SSC to EC

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/team-compass#192]
Report the JupyterLab project status is required (one slide). This is the proposal TBD:

- JupyterLab 3.x

    - Three minor versions released in the past year (3.4, 3.5 and 3.6)
      - Add support for Jupyter Server 2
      - Improve architecture for RTC
      - Add ability to communicate via toast directly in app (not used yet)

- JupyterLab 4 almost out

   - Dev tools and dependencies major upgrade
   - RTC improvements
   - Performance improvements
   - Accessibility improvements
   - New extension manager based on PyPI for easiness
    
- Council has 20 members (as of today)

**Comment by jtpio** [comment]
Closing as completed at the SSC meeting that took place before JupyterCon 2023.
