### ISSUE TITLE
When to release JupyterLab 4?

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/team-compass#193]
At the weekly call, we discuss between releasing the final version of JupyterLab 4 before or after JupyterCon. Some arguments presented were

         * Before:
             * Pro:
                 * Nice for advertisement
                 * Avoid sliding from soon after to in a couple weeks
                 * Allow to upgrade extension without dealing with pre release package
                 * End the long awaiting period for JupyterLab 4
         * After:
             * Pro:
                 * Include work from a bug spring at JupyterCon
                 * Allows to get more bug fixes in
                 * More reactivity to fix new bug reports as people will be back from the conference

The attendees lean towards releasing **before** JupyterCon. If some council members were not able to attend and have a strong feeling to push the release _after_ JupyterCon, please present your argument in this issue for discussion.

cc @jupyterlab/jupyterlab-council

**Comment by jtpio** [comment]
Also, is there a blog post ready to be published after JupyterLab 4 is released?

**Comment by jtpio** [comment]
Closing since JupyterLab 4 has been released: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0
