### ISSUE TITLE
JupyterLab 4 Blog Post

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/team-compass#194]
Now that JupyterLab 4 is released it would be great to get a blog post out in the coming days and weeks.

There has been some work on user facing changes in https://github.com/jupyterlab/jupyterlab/issues/14060 which could be reused.

Last week at JupyterCon there was a talk about the new features in JupyterLab 4 with nice screenshots and screencasts.

**Comment by jtpio** [comment]
As discussed with a couple of JupyterLab council member yesterday during the "release party", it would also be nice to have a `1.0.0` final release of https://github.com/jupyterlab/jupyter_collaboration before publishing the blog post.

**Comment by JasonWeill** [comment]
Here's a roughly 500-word draft, no images, based largely on the changelog: https://docs.google.com/document/d/1GJKNeYPf535LQsGs7JKipvpgSWa7ay3ngeFhJfYwtHk/edit?usp=sharing

Feedback welcome, either here or as comments in the doc.

**Comment by krassowski** [comment]
It would be also good to release the language packs for 4.0 before the blog post.

**Comment by jtpio** [comment]
> It would be also good to release the language packs for 4.0 before the blog post.

Makes sense. Do we have an issue to track this?

**Comment by marthacryan** [comment]
Hi! Just seeing this. Here's a link to our slides: https://docs.google.com/presentation/d/16T6ZD4Pw-U5y9S5bBkEJxFGb7KYdeAUQOfkjxvm6aTY/edit?usp=sharing

**Comment by andrii-i** [comment]
I wanted to thank everyone for the feedback and suggestions in google doc draft (https://docs.google.com/document/d/1GJKNeYPf535LQsGs7JKipvpgSWa7ay3ngeFhJfYwtHk/edit?usp=sharing). There are a couple of outstanding points I'd like to get a further feedback on: 

1. > With binder being so unreliable recently, do we want to link to it?
    > Also, can we put the binder link on a more officially hosted place vs a github gist on a core contributor's account?
    
    by @paddymul

      Given Binder link works every time (at least for me, for now) because it uses jupyterlab pip package (https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7#file-requirements-txt). I agree that it would be  good to put the binder link on a more officially hosted place but not sure what would be a good place. Best official place to put binder link would be jupyterlab repo but [Binder settings](https://github.com/jupyterlab/jupyterlab/tree/main/binder) there assume binder to be used for development and HEAD-of-master is trying to be built on every launch and for me is failing every time.
      
      Are there any more reliable alternatives to Binder (ideally would not require registration like Gitpod as not everyone would go through with it)? What would be a good official place to put binder files instead of https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7? 

2. > I think this was backported to 3.x? If so, we should be careful about claiming it as new in lab 4.

    by @vidartf 

    New settings editor, cell toolbar, and notifications were all back ported to 3.6.x but they are also mentioned in "What's New in JupyterLab 4.0" slides from JupyterCon talk linked above by @marthacryan, were developed during JupyterLab 4 development cycle.

Outside of the two points outlined above, the document looks good to me.

**Comment by andrii-i** [comment]
Since the last update there were no new comments or suggestions so I wanted to share the final draft / blogpost release candidate for your consideration: https://medium.com/@andrii-i/jupyterlab-4-0-0-is-here-bad942758861

The draft remains unchanged from yesterday so I'd like to address a few unresolved points and would welcome any final feedback:

- > It would be also good to release the language packs for 4.0 before the blog post.
   
  Language packs mentioned by @krassowski and @jtpio [here](https://github.com/jupyterlab/team-compass/issues/194#issuecomment-1555881312). @jtpio, @krassowski, could you please provide more context on this? Blogpost seems to be close to done, should we wait for language packs?
- Binder usage: I believe that Binder continues to be a viable solution since it works reliably when not building a new image and has a non-registration policy. 
- Binder link location: Binder link leads to core contributors gist with "launch binder" button. I don't see this as a problem but agree that publishing it in a more formal location may appear more official and trustworthy. Some alternative options: a) change [`jupyterlab/binder` ](https://github.com/jupyterlab/jupyterlab/tree/main/binder) to build latest published package instead of HEAD-of-main (recently fails every time) b) create a new repo in `jupyterlab/` org and publish it there.
- Mentioning features that were back ported to 3.x during 4.0 development as new: this seems consistent as they were developed during JupyterLab 4 development cycle and were are also mentioned in "What's New in JupyterLab 4.0" slides from JupyterCon talk.

Please take a moment to review the final draft and share any thoughts or concerns about points mentioned above.

**Comment by jtpio** [comment]
For Binder we can update https://github.com/jupyterlab/jupyterlab-demo which is usually used for providing "stable" demos of JupyterLab.

And also as mentioned in https://github.com/jupyterlab/team-compass/issues/194#issuecomment-1549071615:

> it would also be nice to have a `1.0.0` final release of https://github.com/jupyterlab/jupyter_collaboration before publishing the blog post.

**Comment by fcollonval** [comment]
> Language packs mentioned by @krassowski and @jtpio https://github.com/jupyterlab/team-compass/issues/194#issuecomment-1555881312. @jtpio, @krassowski, could you please provide more context on this? Blogpost seems to be close to done, should we wait for language packs?

I'm doing the release of the v 4.0.post0 for the language packs right now.

**Comment by fcollonval** [comment]
Done: https://github.com/jupyterlab/language-packs/actions/runs/5099441055

**Comment by krassowski** [comment]
I somewhat disagree with the changes which has been made in the description of extension manager. I proposed edits which try to re-conciliate the old version (which was fine IMO) with improvements which were proposed.

I would love this (or another) announcement to mention the opt-in performance settings which we wanted wider audience to trial before we switch them on by default. I added a suggested paragraph on these to the Google Doc:

> Additional performance improvements are available via opt-in settings. You can help testing them:
> - Faster tab-switching on Chromium browsers
> “Settings” → “JupyterLab Shell” → switch “Hidden mode” to “contentVisibility”
> - Better performance with long notebooks
> “Settings” → “Notebook” → switch “Windowing mode” to “full”

**Comment by andrii-i** [comment]
> it would also be nice to have a 1.0.0 final release of https://github.com/jupyterlab/jupyter_collaboration before publishing the blog post.

@jtpio Thank you for bringing this up. I don't have much context on collaboration work, sorry if following questions are obvious. Is there a release date goal / estimation for https://github.com/jupyterlab/jupyter_collaboration? Do we need to wait for 1.0.0 release taking in account collaboration seems to work as-is?

**Comment by JasonWeill** [comment]
I've made revisions to the JupyterLab 4.0 blog post: https://docs.google.com/document/d/1GJKNeYPf535LQsGs7JKipvpgSWa7ay3ngeFhJfYwtHk/edit#

Note that it's not called "4.0.0" in the blog post, since 4.0.1 is already available. Let's discuss this at the May 31 call.

**Comment by jtpio** [comment]
> Is there a release date goal / estimation for https://github.com/jupyterlab/jupyter_collaboration?

cc @hbcarlos who might know

**Comment by JasonWeill** [comment]
As discussed at the meeting today, I've made a few revisions to the [draft](https://docs.google.com/document/d/1GJKNeYPf535LQsGs7JKipvpgSWa7ay3ngeFhJfYwtHk/edit#):

1. Deleted the Binder promo, to avoid adding load on our limited Binder instance
2. Moved features that are also available in 3.6 to the end, and moved performance earlier (thanks @krassowski)
3. Reinstated the RTC mention; this is in prerelease as a separate repo, and people may ask about it if they expect it to be included with Lab 4.0.

I plan to submit this via Medium early (US PDT) on Friday. It would be good to have a sample image or two, as Medium uses an image in its feeds. (Medium also supports GIFs, although I'd prefer that the primary image be static.)

**Comment by andrii-i** [comment]
[jupyterlab-demo](https://github.com/jupyterlab/jupyterlab-demo)'s PR [#115](https://github.com/jupyterlab/jupyterlab-demo/pull/115) now has working update to JupyterLab 4.0.0 (thanks to @krassowski). But Binder is not caching the image (probably due to limited capacity) and has to build it every time with ~75% failure rate so it's not a stable option.

**Comment by jtpio** [comment]
FYI `jupyter-collaboration==1.0` was released today: https://github.com/jupyterlab/jupyter_collaboration/releases/tag/v1.0.0

I think it would be great to include in the blog post, with a screencast showing 2 users collaborating on the same notebook.

**Comment by jtpio** [comment]
I left a couple of inline comments on the draft.

It looks good :+1: But it would also be nice to add a couple more screenshots or screencasts especially for more visual features. For reference this was the announcement blog post for JupyterLab 3: https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb

**Comment by SylvainCorlay** [comment]
How about have the post be authored by ProjectJupyter directly?

**Comment by JasonWeill** [comment]
I submitted the draft from my own Medium account, so it currently has my name as the author, but I also told @blink1073 and @Ruv7 that I'm OK with it being published as "by Project Jupyter" if that's more suitable. That was previously the norm on the Jupyter blog, though all of the recent articles have had named authors.

**Comment by jtpio** [comment]
Thanks @JasonWeill. Do you have a link to the draft post on Medium so we can over a final review before publishing?

**Comment by SylvainCorlay** [comment]
> I submitted the draft from my own Medium account, so it currently has my name as the author, but I also told @blink1073 and @Ruv7 that I'm OK with it being published as "by Project Jupyter" if that's more suitable. That was previously the norm on the Jupyter blog, though all of the recent articles have had named authors.

How about publishing it from the Jupyter Account, and to list the blog post authors in the end.

**Comment by JasonWeill** [comment]
The blog post is now live, though attributed to me, not to Project Jupyter: https://blog.jupyter.org/jupyterlab-4-0-is-here-388d05e03442

I don't have access to the Jupyter Medium account, but if someone else does, I'd appreciate if they could change the author or republish it on behalf of the project.

**Comment by JasonWeill** [comment]
@SylvainCorlay Thanks for your understanding. I added a paragraph at the end to indicate that this is published on behalf of the community, since we can't change the author after posting.
