### ISSUE TITLE
Council membership and release rights

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/team-compass#204]
### Problem

We have a GitHub team for the JupyterLab council and another one for people with release ability.

There are currently 21 people at the council and 10 in the release team.

We should clarify how we manage people in the release team.
We should keep the list of people with release power as low as possible for security reasons.
We should align PyPI and NPM rights for people within the release team to **all** packages hosted in JupyterLab organization.

**Comment by jtpio** [comment]
For reference the release team was created as a follow-up to https://github.com/jupyterlab/team-compass/issues/167 and the switch to the new Governance model. See https://github.com/jupyterlab/team-compass/issues/167#issuecomment-1467693712 for more context.

It was bootstrapped with a list of people who had made JupyterLab releases in the past, or had expressed in helping with releases. It's a subset of the JupyterLab Council team.

Agree that it would be simpler to align the rights on all platforms. There are still previous maintainers with release rights that should likely be removed from the list as they are not part of the JupyterLab council.
