### ISSUE TITLE
Volunteers to Host Jupyter Community Calls

### ISSUE THREAD

**Issue by tonyfast** [jupyterlab/team-compass#207]
We are looking for volunteers to host monthly Jupyter community calls. We used to run community events, and they were not given the right resources to be sustainable. These events should start with at least two hosts, and in time more hosts should be trained. @isabela-pf has created a bunch of resources to help run these events https://github.com/isabela-pf/jupyter-communitycalls . Let's get this show back on the road.

I have volunteered myself to run these meetings, and we'll start doing them once we have another volunteer to host. Reply in this thread to volunteer or ask any questions.

**Comment by krassowski** [comment]
Hi @tonyfast, should we move this issue to a project-wide repository for more visibility?

I am unable to help at the time as they were happening in the past until December (which is also why I was not able to join any of them in the past except for maybe two during hoilday seasons), I _might_ be able to help starting in January.

**Comment by krassowski** [comment]
Also, it seems that @isabela-pf's repo is 50 commits behind this one: https://github.com/Quansight-Labs/jupyter-communitycalls.

**Comment by tonyfast** [comment]
i was really hoping we could do this without governance. as you mention, running an effort around this time of year could be difficult logistically. gonna close this as i'm a little less motivated than when i initially offered. if the desire returns i'll open it back up.
