### ISSUE TITLE
Vote on Mermaid graph renderer for Markdown cells

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/team-compass#208]
At the July 26th meeting, it was decided to call for a vote on adding support to render mermaid JS code block as graph in Markdown cells: https://github.com/jupyterlab/jupyterlab/pull/14102

> FYI there is a related JEP opened: https://github.com/jupyter/enhancement-proposals/pull/101 - that will probably not make it. This means the standard will not require mermaid JS code block to be rendered as graph by notebook clients. But notebook clients can add that feature as it does not impact the notebook format used.

---

The vote will be closed on **August 20th** at midnight anywhere on earth (or as soon as we reach majority).

The question: Should we render mermaid JS code block as graph in Markdown cells?

The vote:

- @ellisonbg:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @fperez:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ivanov:
  - [ ] Yes
  - [x] No
  - [ ] Abstain
- @afshin:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @jasongrout:
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @echarles:
  - [ ] Yes
  - [ ] No
  - [x] Abstain
- @jtpio:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @damianavila:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @blink1073:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @krassowski:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @marthacryan:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @fcollonval:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ajbozarth:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ohrely:
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @jess-x:
  - [ ] Yes
  - [ ] No
  - [x] Abstain
- @hbcarlos:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @andrii-i:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @mbektas:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @isabela-pf:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @JasonWeill:
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ericsnekbytes:
  - [x] Yes
  - [ ] No
  - [ ] Abstain

**Comment by fperez** [comment]
As a reference, [MyST tools are being updated to match this](https://github.com/executablebooks/mystmd/pull/529), so we have good convergence of the approaches. Ultimately this will mean that both the live in-notebook experience and any export made by MyST will give users a consistent experience. 

Thx to @rowanc1 for the work on the MyST side.

**Comment by ellisonbg** [comment]
@fperez thanks for the details about MyST, that helps.
