### ISSUE TITLE
December 13, 2023 Jupyter Community Call @ 9am PST

### ISSUE THREAD

**Issue by tonyfast** [jupyterlab/team-compass#223]
We have no had a community call this year and have missed the opportunity to appreciate what the community is doing with out tools.

I'm proposing to shuffle the schedule on December 13 to host a community during the JupyterLab meeting time from 9am-10am PST. @krassowski  mentioned the JupyterLab team needs to have a triage meeting with will occur from 8:30am-9:00am PST. 

i'd like to confirm that this change for 12/13 by 11/27. are there any objections to this one time change to run a community event?

get your demos ready!

**Comment by fcollonval** [comment]
I don't have any objections

**Comment by tonyfast** [comment]
- [ ] create an agenda
 - [ ] sign up sheet for talks
- [ ] social media announcements

**Comment by tonyfast** [comment]
thanks for sending these resources @RRosio 

i've just added the agenda and changed the calendars.

**Comment by tonyfast** [comment]
i'm going to need support announcing the date and agenda on twitter, discourse, and the mailing list. 

@andrii-i do you think you could help draft some social media send out and let folks know there is room to sign up for talks.

**Comment by tonyfast** [comment]
aww. im so stoked you are stoked! 

thanks for that advice. i was looking for how to contact the contact the community at large, but it is not apparent how to do that. i'll start with this email.

**Comment by Ruv7** [comment]
Heads up I met a recent graduate who was asking me for advice on how to connect with JupyterLab folks. I've emailed her with a link to this issue but if you can at mention me here when something some more short and buzzy is created I'm happy to forward to her.

**Comment by amoghak-ds** [comment]
Appreciate the shout-out, Ana!

Hello everyone! I'm Amogha Kancharla, based in India. I'm excited to embark on my open-source journey and connect with this amazing community. While I may not have as much experience as some of the seasoned individuals here, I'm eager to contribute value, share insights, and collaborate on interesting projects. You can catch up with me:  here


Looking forward to learning and growing together!

**Comment by amoghak-ds** [comment]
Sorry about the link. 

 It's http://linkedin.com/in/amoghakancharla

**Comment by tonyfast** [comment]
here are 2 versions of announcements.

folks can sign up for talks by adding their name to the agenda.

@Ruv7 @blink1073 @andrii-i could the social media group send out some announcements for the event next week?

---
# html version

## Upcoming Call

December 13, 2023, at 9:00AM PST (your [timezone](https://arewemeetingyet.com/Los%20Angeles/2023-12-13/9:00/Jupyter%20Community%20Call))

* Agenda (add yourself) on [HackMD](https://hackmd.io/h_S-qpfsQgS_HFewzJvI5g) 
* Meet on [Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)

_What is the Jupyter Community Call?_

Think of it as a **"virtual JupyterCon**". It's a place to announce and share fun things happening in the Jupyter community. We meet on Zoom (over video) and:

* anyone can attend (for free!) 👩🏾‍🚒 👨🏼‍🍳 👨🏽‍🎤 👩🏻‍🚀 👮🏻‍♂️ 🕵🏾‍♀️ 👨🏿‍💻 👩🏻‍⚕️ 👩🏼‍🌾 👨🏻‍⚖️ 👩🏽‍🔬
* 🖼 anyone can present (**add yourself the agenda above**)
* 👀 anyone can just *sit in on the call*.
* presenters will lead a demo and spend a few minutes answering questions
* topics will be targeted at a broad Jupyter audience (not overly technical)

Watch previous calls from this [YouTube Playlist](https://www.youtube.com/playlist?list=PLUrHeD2K9Cmkoamm4NjLmvXC4Y6E1o8SP).

---

## markdown version

```markdown
## Upcoming Call

December 13, 2023, at 9:00AM PST (your [timezone](https://arewemeetingyet.com/Los%20Angeles/2023-12-13/9:00/Jupyter%20Community%20Call))

* Agenda (add yourself) on [HackMD](https://hackmd.io/h_S-qpfsQgS_HFewzJvI5g) 
* Meet on [Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)

_What is the Jupyter Community Call?_

Think of it as a **"virtual JupyterCon**". It's a place to announce and share fun things happening in the Jupyter community. We meet on Zoom (over video) and:

* anyone can attend (for free!) 👩🏾‍🚒 👨🏼‍🍳 👨🏽‍🎤 👩🏻‍🚀 👮🏻‍♂️ 🕵🏾‍♀️ 👨🏿‍💻 👩🏻‍⚕️ 👩🏼‍🌾 👨🏻‍⚖️ 👩🏽‍🔬
* 🖼 anyone can present (**add yourself the agenda above**)
* 👀 anyone can just *sit in on the call*.
* presenters will lead a demo and spend a few minutes answering questions
* topics will be targeted at a broad Jupyter audience (not overly technical)

Watch previous calls from this [YouTube Playlist](https://www.youtube.com/playlist?list=PLUrHeD2K9Cmkoamm4NjLmvXC4Y6E1o8SP).
```

**Comment by tonyfast** [comment]
@ericsnekbytes mentioned he could announce to discourse and other services. thanks for offering your help. could you share links to any references you make please?

**Comment by andrii-i** [comment]
@tonyfast @ericsnekbytes as started to mention during the call, please send your requests for blogpost or social media publishing to jupyter-media-strategy@googlegroups.com. Please make sure to include the text that you want to be posted and where it should be posted (blog and/or social media).

**Comment by ericsnekbytes** [comment]
@tonyfast  Does this look good? I'll follow up by posting on Discourse, Reddit and submitting it for the blog.

## Upcoming Open Community Call

We want to see all the cool things you're doing with Jupyter, so we're holding an open call with the community for people to chat, and share their creations and work. Think of it as a "virtual JupyterCon": It's a place to announce and share fun things happening in the Jupyter community.

Event Details:

December 13, 2023, at 9:00AM PST (your [timezone](https://arewemeetingyet.com/Los%20Angeles/2023-12-13/9:00/Jupyter%20Community%20Call))

- Agenda (add yourself) on [HackMD](https://hackmd.io/h_S-qpfsQgS_HFewzJvI5g) 
- Meet on [Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)

We meet on Zoom (over video) and:

- Anyone can attend (for free!) 👩🏾‍🚒 👨🏼‍🍳 👨🏽‍🎤 👩🏻‍🚀 👮🏻‍♂️ 🕵🏾‍♀️ 👨🏿‍💻 👩🏻‍⚕️ 👩🏼‍🌾 👨🏻‍⚖️ 👩🏽‍🔬
- 🖼 Anyone can present (add yourself the agenda above)
- 👀 Anyone can just sit in on the call.
- Presenters will lead a demo and spend a few minutes answering questions
- Topics will be targeted at a broad Jupyter audience (not overly technical)

**Comment by tonyfast** [comment]
LGTM that would work for reddit, discourse, and medium (if the past video links are added)

**Comment by andrii-i** [comment]
Thank you @ericsnekbytes

**Comment by Ruv7** [comment]
Quick question. Has a Discourse post happened yet? If so, can someone share the link?

**Comment by tonyfast** [comment]
@ericsnekbytes posted it and @choldgraf pinned it 

https://discourse.jupyter.org/t/upcoming-open-community-call/22773/1

**Comment by tonyfast** [comment]
is there someone that can make a twitter and/or mastodon post please?

**Comment by Ruv7** [comment]
@tonyfast Yes, my apologies. I was working on this yesterday and then Mexico City decided to have an earthquake and it derailed my afternoon. Are you planning to make a blog post out of this or should I use the Discourse announcement? We ideally prefer to link to blog posts but I understand if due to time constraints that's not possible.

**Comment by Ruv7** [comment]
That blog post draft needs work, this is something I had hoped to copy/paste but it needs a bit of work. Also if any you wants to have their name associated with the blog post I wanted to offer that up. Otherwise I can use the Jupyter voice and post from the Jupyter account. Let me know what you prefer.

**Comment by Ruv7** [comment]
I'll work on this now.

**Comment by Ruv7** [comment]
Arg. I had created a blog post from the Jupyter voice yesterday as a draft and now I can see in email that you had sent me another link. Stay tuned. I'll send links shortly.

**Comment by ericsnekbytes** [comment]
Thanks. If it helps/it's faster, you can post it with my name as the author on the Jupyter blog. I don't know how that works though, so let me know if this is preferred and I can work on figuring it out.

**Comment by Ruv7** [comment]
I personally prefer to give you credit for the post by having your name associated to it. In looking at what you sent you need to submit your story to the Jupyter publication. Here are instructions for doing so: https://help.medium.com/hc/en-us/articles/213904978-Add-a-draft-or-post-to-publication

**Comment by JasonWeill** [comment]
The new convention with hashtags is to interCap them so that screen readers can read them properly. With that change applied, and copy edits, how about:

> We want to see all the cool things you're doing with Jupyter! Join our next Jupyter Community Call, on December 13 at 9:00 am PST (17:00 UTC), to chat, have fun, and share your work. It'll be like a mini virtual JupyterCon. See you soon! (provide link to Discourse post) #jupyter #jupyterLab #jupyterNotebook #projectJupyter #communityCall #openSource #oss

**Comment by Ruv7** [comment]
Works for me, thanks for sharing. I am not keen to include Lab and Notebook as hashtags without including the other 8 subprojects since the call could include any of those topics. Is there such a thing as too many hashtags?

**Comment by Ruv7** [comment]
Also, this was sent to me by @ericsnekbytes so I'll want his go ahead before using the new content.

**Comment by ericsnekbytes** [comment]
Jason's text looks good (I think those are two high profile apps that will probably draw a lot of attention so I'm in favor of leaving them in). I'll work on submitting the medium post according to those instructions :)

**Comment by ericsnekbytes** [comment]
@Ruv7 I think I need to be added to the publication as a writer on Medium, is that something you can do? (feel free to post as not-me with any edits you think are appropriate if that would be faster/easier).

**Comment by Ruv7** [comment]
Let me add you as a writer.

**Comment by Ruv7** [comment]
Done. Try again please.

**Comment by ericsnekbytes** [comment]
Okay, it's the blog post is submitted on Medium to the Jupyter publication.

**Comment by Ruv7** [comment]
Take a look: https://blog.jupyter.org/open-community-call-b93d44fc5856 Do you see anything you want to change? If not I'll go ahead and blast out on social media.

**Comment by ericsnekbytes** [comment]
That looks good, let's publish! Thanks.

**Comment by Ruv7** [comment]
Heads up that X/Twitter had to be cut back in order to meet character limits.

**Comment by ericsnekbytes** [comment]
Thanks for making this happen @Ruv7 :)

**Comment by ericsnekbytes** [comment]
I'm trying to help [this person](https://www.reddit.com/r/JupyterLab/comments/18cczkp/upcoming_open_community_call/) add their name to the agenda, do they need a a HackMD account to add things?

**Comment by tonyfast** [comment]
Currently the hackmd is set up for signed in users to write to the document. So if they are signed in to hackmd (with GitHub Google etc) they should be able to edit. If not maybe you could pencil in their name.

**Comment by ericsnekbytes** [comment]
Okay, I offered to add them in my reply, so we'll see if they respond 👍

**Comment by JasonWeill** [comment]
@tonyfast I've signed in as Project Jupyter

**Comment by tonyfast** [comment]
thanks so much for handling the recording. it was one less thing to worry about and it helps direct my energy towards the event.

we'll now use this issue to handle post meeting working.

- [ ] upload the video
- [ ] share link on social 1 week afterwards
- [ ] share link on social 2 week afterwards

**Comment by tonyfast** [comment]
@JasonWeill thanks again for volunteering to record the event. let me know if you get a chance to upload the content. i can draft a blog post and we can start to put that through the process.

**Comment by JasonWeill** [comment]
I recorded the call via Zoom, although I don't typically upload the content to our YouTube channel. @afshin are you still uploading recorded calls, or does someone else do that?

**Comment by tonyfast** [comment]
i appreciate you kicking the ball on this one.

**Comment by isabela-pf** [comment]
Typically we uploaded in batches and someone would volunteer as needed; there wasn't a single process I was aware of at least. I have the time to upload right now, so I'll handle this one (and reach back out if I don't have the permissions I think I do).

Thanks for bringing it up!

**Comment by isabela-pf** [comment]
I updated it in the to do list in an above comment, but

- [Meeting recording's on youtube](https://youtu.be/hUU77BfU-Kk)
- [PR for agenda/notes](https://github.com/jupyter/jupyter/pull/720) for all of 2023 is up
- Discourse post has been updated.
- I couldn't find an issue on the jupyterhub/team-compass to close, so I think that one's good to go. 
- I've reached out to the media strategy group about posting to social accounts.

Hope that helps!

**Comment by tonyfast** [comment]
![image](https://github.com/jupyterlab/team-compass/assets/4236275/aa61d9ec-1548-41cf-8788-9a402a17fa0e)

@isabela-pf the title image guys you made for the december call are adorable!!! thank you so much do doing all this work. these pull requests basically close out the post meeting work. i think we can close this issue now or afterwards.

this whole event was an incredible team effort. the distributed care made for a phenomonal event. it was a privilege to participate in. it meant a lot to be able to organically produce something a significant scale. thanks to everyone that contribute to the pre-meeting, meeting, and post-meeting efforts. i hope y'all can build on this momentum.

**Comment by Ruv7** [comment]
Thank you @tonyfast for being the spark that got this going! I thought it went really well also and I was thrilled to see so many people come together to make it happen. There is interest in a January call and I'll provide an update once I have a volunteer leader and some more news.

**Comment by tonyfast** [comment]
i'm sure there wasn't anything specific about my contribution a "spark". to be clear, its more like the last :fire: left in a torch i've been carrying all year! i started advocating for communtiy calls after isabela wasn't finding community support to continue the community calls. we both discussed that these events would be most sustainable with 2 hosts. earlier this year, i said i'd run a community call if another person hosted. i posted an issue AND went to several development meetings to solicit hosts. i visited executive council and steering council meetings. i advocated for the importance of these events as a community glue for the entire year. often my asks were dismissed because the last of formal governance around community was often the focus. so to break the spell of isolation jupyter has from its users i hosted the community call with the last of the fuel in the torch.

i'm really, really happy that the community committee is formed and can now start serving our developers and users. it is great that this event is worthy of continued interest. but, we need to acknowledge that there is no spark that makes community calls happen. it is concerted, collective effort from people like Zach and Isabela who made all the resources so i didn't need to expend as much energy running this event. the community call has been smoldering for years and i hope you all can give it the oxygen it deserves. i do not plan to run another community call, but i am here to support any of the future hosts running this challenging event. i really hope that people will reach out to me, zach, or isa so we can ensure we are building on each others efforts collaboratively.
