### ISSUE TITLE
(Lab council) Vote to merge the Notebook weekly meeting with the Lab weekly meeting

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyterlab/team-compass#232]
name: "Merge the Notebook/Lab meetings"
about: Merging the weekly Lab and Notebook meetings
---

This proposal calls for merging the Notebook weekly meeting with the Lab weekly meeting, as discussed previously [here (Lab)](https://github.com/jupyterlab/team-compass/issues/230) and [here (Notebook)](https://github.com/jupyter/notebook-team-compass/issues/30).

The meeting name will be decided later, but "Jupyter Frontends" will be used tentatively until a decision can be made.

- @ohrely
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @mbektas
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @gabalafou
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @ericsnekbytes
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @echarles
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @brichet
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @andrii-i
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @JasonWeill
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @ellisonbg
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @fperez
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @ivanov
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @afshin
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @jasongrout
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @jtpio
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @damianavila
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @blink1073
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @krassowski
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @marthacryan
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @fcollonval 
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @mbektas 
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @isabela-pf  
  - [ ] Yes
  - [ ] No
  - [x] Abstain
- @ajbozarth 
  - [ ] Yes
  - [ ] No
  - [ ] Abstain

**Comment by echarles** [comment]
This is about merging the meeting, not the councils, right? Is there an intent in a short time to merge also the councils? (see https://github.com/jupyter/notebook-team-compass/issues/30#issuecomment-1896282156)

**Comment by jtpio** [comment]
> This is about merging the meeting, not the councils, right? Is there an intent in a short time to merge also the councils? (see [jupyter/notebook-team-compass#30 (comment)](https://github.com/jupyter/notebook-team-compass/issues/30#issuecomment-1896282156))

This is the issue discussing it: https://github.com/jupyterlab/team-compass/issues/230

**Comment by krassowski** [comment]
@echarles there is also a draft/placeholder PR for merging councils: https://github.com/jupyter/governance/pull/200; from the discussion in the lab call it appears that merging councils would be a vote from SSC + EC rather than from the subprojects themselves (although likely conditional on whether there is a consensus on it within the subprojects)

**Comment by ellisonbg** [comment]
Seem like things would be simple if we merge and then elect a new SSC rep of the merged council.

**Comment by echarles** [comment]
> Seem like things would be simple if we merge and then elect a new SSC rep of the merged council.

Hi Brian, I have posted more inputs after thinking about it on https://github.com/jupyter/notebook-team-compass/issues/30#issuecomment-1898085907 Let's just let the current vote go on and I am happy to handle the potential merge with the new JupyterLab SSC representative.

**Comment by jtpio** [comment]
> Seem like things would be simple if we merge and then elect a new SSC rep of the merged council.

This was also the general feeling when this topic was discussed yesterday during the JupyterLab call :+1:  https://github.com/jupyterlab/team-compass/issues/229#issuecomment-1896983165 

For reference, we are working on populating the text for the proposal in https://github.com/jupyter/governance/pull/200, so it can be ready for review very soon.

**Comment by jtpio** [comment]
Quorum has been met with a majority of "Yes". Closing as fixed!
