### ISSUE TITLE
(Lab council) Vote to revise the JupyterLab major version lifecycle

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/team-compass#235]
name: "Revise the JupyterLab major version lifecycle"
about: Revise JupyterLab's major version lifecycle to end maintenance one year after the next major version has its first generally available release
---

Discussed in https://github.com/jupyterlab/team-compass/issues/231

Proposal:

1. Adopt a revision to the JupyterLab release cycle: a major version of JupyterLab will receive updates until one year after the following major version's first generally available release.
2. To aid in the transition, JupyterLab 3 will continue to publish patch releases to address low-risk critical bug fixes for three months after its nominal end of maintenance date of May 15, 2024.

Low-risk critical bug fixes are defined as those that:

- address a critical issue (security, data loss, etc.)
- be reasonably small/low complexity so their vetting and review doesn't require a massive work investment and has low potential to open doors for new vulnerabilities/bugs
- perhaps checked by at least two maintainers? (not sure about this one)

Per the [Jupyter decision-making guide](https://github.com/jupyter/governance/blob/main/decision_making.md), "After the proposal is seconded by another member of the council, members have seven days to vote."

## Votes

- @ohrely
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @mbektas
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @gabalafou
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @ericsnekbytes
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @echarles
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @brichet
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @andrii-i
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @JasonWeill
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @ellisonbg
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @fperez
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @ivanov
  - [ ] Yes
  - [ ] No
  - [x] Abstain
- @afshin
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @jasongrout
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @jtpio
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @damianavila
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @blink1073
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @krassowski
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @marthacryan
  - [ ] Yes
  - [ ] No
  - [ ] Abstain
- @fcollonval 
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @mbektas 
  - [x] Yes
  - [ ] No
  - [ ] Abstain
- @isabela-pf  
  - [ ] Yes
  - [ ] No
  - [x] Abstain
- @ajbozarth 
  - [x] Yes
  - [ ] No
  - [ ] Abstain

**Comment by JasonWeill** [comment]
@jupyterlab/jupyterlab-council Please vote above! Once someone has seconded this proposal, the team will have 7 days to vote.

**Comment by andrii-i** [comment]
Voted "yes." We need to make sure we notify numerous impacted JupyterLab 3 users about the change. 

Do we have anything planned for it? In my opinion we should use experience of Notebook 7 release and communication around it including warning via banner in UI and text in terminal for users of older versions.

**Comment by JasonWeill** [comment]
I have a draft blog post about it; if approved, we should publish it and mention it, ideally multiple times, on social media.

**Comment by ivanov** [comment]
I am not opposed to this change, but I would encourage reflection on whether JupyterLab should release major versions as frequently as it does, given the concern for a large chunk of users still on JupyterLab 3. For example, browsers release major version at an even faster clip, but their functionality, including 3rd party extensions typically continue to work without users being aware of what version they are on.

**Comment by krassowski** [comment]
There might be _some_ backlash, which I infer from seeing comments by users testing 4.0.x seeing regressions, including critical regressions still not being addressed. [29 out of 49](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3Atag%3ARegression+milestone%3A4.0.x) issues describing regressions introduced in 4.0.0 remain open. I would like to acknowledge the regressions in the announcement, add a call for action, and promise to review PRs which address the regression as a priority.

> The fix is approved by at least two JupyterLab maintainers

I don't think this is realistic, unless we can get more council members to review regularly (even 1 review each month would  be great).

**Comment by JasonWeill** [comment]
I revised the draft blog post's Google Doc to reflect @krassowski 's comments: https://docs.google.com/document/d/1jO-MksEAQwcGS_u0oXGCY9NNSfS6FeNA2h86nXxQAoM/edit

I left open the comment about two ship-its being required; I'm OK with only one approval, and I'm curious about what other council members think.

**Comment by JasonWeill** [comment]
@jupyterlab/jupyterlab-council A quick reminder to please vote if you haven't already! The typical vote duration is 7 days, so let's decide on Wednesday, February 7, anywhere on Earth.

**Comment by JasonWeill** [comment]
Of 22 council members, the results as of this morning are:

* 13 **Yes**
* 0 **No**
* 2 **Abstain**
* 7 **not voting**

The quorum is met (68% participation, minimum 50%) and a majority of nonblank votes are "Yes". Per the [decision-making guide](https://github.com/jupyter/governance/blob/main/decision_making.md), this vote **passes**.
