### ISSUE TITLE
Removing stale branches in `jupyterlab`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/team-compass#236]
Hi, I would like to clear up some [stale branches](https://github.com/jupyterlab/jupyterlab/branches/stale) which are fetched on cloning the repo adding to the general noise and time it takes to fetch (including on CI):

- https://github.com/jupyterlab/jupyterlab/tree/datastore-notebook-model 91 commits, no PR,  last commit 5 years ago
- https://github.com/jupyterlab/jupyterlab/tree/restart-and-run-icon 10 commits, last commit 4 years ago
- https://github.com/jupyterlab/jupyterlab/tree/input-deadlock 6 commits, no PR, last commit 3 years ago
- https://github.com/jupyterlab/jupyterlab/tree/publish-pw-report 0 commits, no PR

Unless other suggestions are provided, in 2 weeks from today (on Feb 14th) I will open PRs for stale branches that had no PR associated to ensure that the work in there is archived by GitHub and then immediately delete all the stale branches listed above. If anyone raises any objections we can vote or decide to do something else with these.

**Comment by jtpio** [comment]
> I will open PRs for stale branches that had no PR associated to ensure that the work in there is archived by GitHub and then immediately delete all the stale branches listed above.

Thanks @krassowski, that sounds like a good approach :+1:

**Comment by fcollonval** [comment]
Thanks @krassowski sounds good to me too.

I removed the `publish-pw-report` that I probably created by mistake on core instead of my fork.

**Comment by krassowski** [comment]
Closing as done, all stale feature branches have been deleted.
