### ISSUE TITLE
JupyterLab Calendar

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/team-compass#24]
Hey y'all,

I created a JupyterLab Google Calendar for posting meetings and events. I've shared ownership with @blink1073, @ellisonbg, @jasongrout, and @afshin. This calendar is being used by the Project-wide Jupyter calendar in jupyter/jupyter#469 to display information about JupyterLab to the broader Jupyter community. As you add/remove events, they will be shown on the main Jupyter readthedocs page.

https://calendar.google.com/calendar/embed?src=dgpd36f43et9grabn6tdin6pmc%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by blink1073** [comment]
Looks great, thanks @Zsailer!

**Comment by Zsailer** [comment]
I added the JupyterLab dev meeting, Dec 2-6th, to the calendar.
