### ISSUE TITLE
Should Lab calls continue to be recorded? When will previous calls be posted?

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/team-compass#241]
As of this morning, the most recent videos on the [Jupyter / IPython YouTube channel](https://www.youtube.com/@ipython/videos) are:

1. [The Jupyter Community Call from December 13, 2023](https://www.youtube.com/watch?v=hUU77BfU-Kk)
2. [The JupyterLab team meeting from August 2, 2023](https://www.youtube.com/watch?v=fLl3GeQljCE)

We've been recording the on-the-record portions of Lab calls since then. Should we continue to record these? If so, who owns the task of posting them to the YouTube channel?

**Comment by jtpio** [comment]
cc @afshin who might know more

**Comment by afshin** [comment]
Hi @JasonWeill @jtpio. The videos are available for download by logging into our Zoom account (via the web interface) – the credentials are in the 1Password.

The YouTube account is a "brand" account for Jupyter/IPython and all the recent years' worth of JupyterLab videos you see were posted by me, probably. I think the brand account delegation requires a Google account and also is *not* something we can easily store in 1Password. For now, I have added @jtpio's account to have manager access on our brand account. This means that when you're signed into your account and on YouTube, you should be able to switch to the Jupyter/IPython brand account and post videos for it. I hope this helps!

**Comment by jtpio** [comment]
Thanks @afshin!

> The videos are available for download by logging into our Zoom account (via the web interface) – the credentials are in the 1Password.

What is the process to get access to the 1Password? (I don't have access to it currently)

**Comment by afshin** [comment]
I don't know whether we have an official process, it still seems some of this is a bit ad hoc, but I've invited you to the 1Password org.

**Comment by jtpio** [comment]
FYI I was able to upload a few recordings to the YouTube channel. Thanks!

Will try to go through the backlog over the next days / weeks. Starting with the oldest videos just in case older recordings might be removed from Zoom.

**Comment by jtpio** [comment]
> Will try to go through the backlog over the next days / weeks. Starting with the oldest videos just in case older recordings might be removed from Zoom.

Actually went through all of them at once, we should now be all caught up!

![image](https://github.com/jupyterlab/team-compass/assets/591645/8a4cab18-bc21-4797-a237-4560550bc5a9)


Here is the "JupyterLab Meetings" playlist: https://www.youtube.com/playlist?list=PLUrHeD2K9Cmmqo4iejSeXfAoMz_bO-JRr. Newer videos are at the bottom, but maybe we could change the order to show newer videos at the top instead.

**Comment by JasonWeill** [comment]
Thank you so much, @jtpio ! 🎉

**Comment by JasonWeill** [comment]
Now that we're caught up, should we close this issue? Anything more to do?

**Comment by jtpio** [comment]
I think we can close it yes.

We might want to add the links to the videos on the meeting notes issue: https://github.com/jupyterlab/team-compass/issues/229. But that's going to be quite tedious (unless there is a way to write a small script to do that). For the next meetings we try to upload the video sooner, and add the link to the meeting notes directly.
