### ISSUE TITLE
Reminder: JupyterLab meeting happening Thursday this week, not Wednesday.

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/team-compass#33]
Reminding everyone that we'll be meeting **Thursday** at 9am Pacific (January 2nd, 2020) this week—*not the usual Wednesday morning*—since tomorrow is a holiday for many. 

Remember, you can follow the [JupyterLab google calendar](https://calendar.google.com/calendar/embed?src=dgpd36f43et9grabn6tdin6pmc%40group.calendar.google.com&ctz=America%2FLos_Angeles) to stay up-to-date.

**Comment by telamonian** [comment]
I had completely forgotten we said that. Thanks for the reminder!
