### ISSUE TITLE
Jupyterlab, Jupyter Lab, or JupyterLab?

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/team-compass#43]
At the Jupyterlab dev meeting in Austin last year we had a short discussion about what the canonical Jupyterlab spelling/capitalizing is. I remember the discussion but not where we landed.

So did we land anywhere definite on this? 

Are we Jupyter building Jupyterlab? 
Are we Jupyter building Lab? JupyterLab?
    - If this is is the case why do we pip install ```jupyterlab```, but launch ```jupyter lab```

I've been thinking about branding surrounding JupyterLab a bit lately and I wanted to have a discussion.

**Comment by jasongrout** [comment]
I've always thought it was JupyterLab, abbreviated JLab or jlab, and the command is that way because it would be onerous to type `jupyter jupyterlab`

**Comment by jasongrout** [comment]
Since there was no more discussion, closing as resolved. Thanks!
