### ISSUE TITLE
Migrating jtpio/jupyterlab-extension-examples to jupyterlab/extension-examples

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/team-compass#44]
Together with @echarles and @fcollonval, we have taken over the work initiated by @MMesch on building a set of extension examples for JupyterLab. They are currently living in the following repository:

https://github.com/jtpio/jupyterlab-extension-examples

As mentioned in the last developer call, we have been making significant progress recently, and we think it's now in a good shape to consider migrating it over here. Also the recent 2.0 release makes it a good time to bring that up, as the community will be looking into updating existing extensions, or creating new ones.

Even though we haven't really publicly communicated about it yet, it has already been proven useful to some developers:

- https://discourse.jupyter.org/t/how-to-custom-cell/1280/5
- https://twitter.com/micahjsmith/status/1233070629642997761
- 38 stars on GitHub as of 2020/03/11

We think this resource could be made even more visible by migrating the repository over to the [jupyterlab organization](https://github.com/jupyterlab). Links and references can then be added to the documentation to point to these extra materials.

This set of extensions is not meant to replace the JupyterLab documentation. Instead it provides an alternative way to learn how to make an extension: by running example code and trial and error.

### Criteria for official subprojects

All criteria might not apply for this particular repository, but since it is mentioned in #12 we can go over the list here:

> Have an active developer community that offers a sustainable model for future development.

As of today (2020/03/11), there has been 4 contributors to the project. 3 of them are active in the JupyterLab ecosystem and have authored several JupyterLab extensions.

> Have an active user community.

The targeted user community is identical to the one targeted by the JupyterLab documentation and the [apod tutorial](https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html).

> Use solid software engineering with documentation and tests hosted with appropriate technologies (Read The Docs and Travis are examples of technologies that can be used).

All examples are documented, linted, formatted, and CI ensures the configs are identical for all examples. CI also checks the embedded code snippets are up-to-date. See https://github.com/jtpio/jupyterlab-extension-examples/pull/71/checks as an example.

All examples follow the structure of the [TypeScript Cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts), and the [Server Extension TypeScript Cookiecutter](https://github.com/fcollonval/cookiecutter-jupyterlab-extension-with-serverextension) for the server extension example.

PRs are reviewed by at least one other person.

Maintenance wise, the procedure to update the examples to support the latest JupyterLab version is similar as the one used to update the cookiecutter repositories and the extension tutorial.

> Demonstrate continued growth and development.

There is a growth in interest for this kind of resource and [documentation issues](https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3Atag%3ADocumentation) in the JupyterLab repo.

> Integrate well with other official Subprojects

This complements the existing JupyterLab documentation.

> Be developed according to the Jupyter governance and contribution model that is documented here

The contributing guide can easily be extended to make these points more visible.

> Have a well-defined scope.

See https://github.com/jtpio/jupyterlab-extension-examples#tldr.

> Be packaged using appropriate technologies such as pip, conda, npm, bower, docker, etc.

The examples are not packaged and released (out of scope).

### References

- Meta issue to track the progress: https://github.com/jtpio/jupyterlab-extension-examples/issues/22
- Improve and extend documentation - for developers: https://github.com/jupyterlab/jupyterlab/issues/7273
- [DISCUSS] Create a `jupyterlab-extension-examples` repository : https://github.com/jupyterlab/jupyterlab/issues/7505
- Document process for adding new jupyterlab repos: #12
- Previous issue about migrating a project to the `jupyterlab` organization: https://github.com/jupyterlab/team-compass/issues/10

**Comment by afshin** [comment]
I think this is a great idea 👍 

`https://github.com/jupyterlab/extension-examples`

**Comment by jasongrout** [comment]
> We think this resource could be made even more visible by migrating the repository over to the [jupyterlab organization](https://github.com/jupyterlab). Links and references can then be added to the documentation to point to these extra materials.

Definitely +1 from me!

**Comment by saulshanabrook** [comment]
So excited about this! Thank you ❤️

**Comment by ian-r-rose** [comment]
Big 👍

**Comment by blink1073** [comment]
Thanks for the hard work and the thoughtful proposal @jtpio!  👍

**Comment by jasongrout** [comment]
It looks like so far the sentiment is overwhelmingly positive (8 responses). How about we leave this open one more day for anyone else to flag any concerns before moving forward with it?

**Comment by jtpio** [comment]
Thanks everyone for the positive feedback!

Let me know when it's time to move forward with it.

**Comment by jasongrout** [comment]
No objections have been voiced. I think it's time to move forward. Do you want to work with Sylvain to transfer the repo over? I can help tomorrow if you want as well.

**Comment by jasongrout** [comment]
This is done now: https://github.com/jupyterlab/extension-examples/
