### ISSUE TITLE
Proposal: Move pytest-check-links to the JupyterLab org

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#46]
We depend on pytest-check-links for our CI builds.  Currently it is on @minrk's personal profile.  He has [agreed](https://github.com/minrk/pytest-check-links/issues/8#issuecomment-605840063) that we should move it here so that we can help maintain it.

**Comment by bollwyvl** [comment]
Rad. I'm interested in doing some work on it... anchors, rate limiting,
fixing up those deprecation warnings.

**Comment by jasongrout** [comment]
Sounds good to me

**Comment by afshin** [comment]
👍

**Comment by bollwyvl** [comment]
I have also been meaning it to add to conda-forge, but want to get the
aforementioned warning-per-link cleaned up.

**Comment by jasongrout** [comment]
This is now done: https://github.com/jupyterlab/pytest-check-links
