### ISSUE TITLE
Is there a JupyterLab team?

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/team-compass#47]
One of the things that the JupyterHub team compass is used for is to have a public record of who are "core team" members (https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html). This is helpful for giving credit to individuals on the team, as well as giving them credibility to engage with other projects, get funding, and interact productively in repositories etc.

Does JupyterLab have something like this? If somebody asked me "who is on the jupyter lab team?" is there a place I could send them to?

(the reason I'm asking is because somebody asked me this, and I had no idea what to tell them)

**Comment by timkpaine** [comment]
https://github.com/jupyterlab/team-compass/

**Comment by timkpaine** [comment]
https://github.com/jupyterlab/jupyterlab#team

**Comment by jasongrout** [comment]
I would say it's not up to date, though.

**Comment by choldgraf** [comment]
(also, FWIW, not very discoverable)

**Comment by jtpio** [comment]
Closing as there is now a list of council members: https://jupyterlab-team-compass.readthedocs.io/en/latest/team.html
