### ISSUE TITLE
JupyterLab debugger extension

### ISSUE THREAD

**Issue by afshin** [jupyterlab/team-compass#5]
## Background

We have had a number of conversations about adding variable inspection and code debugging tools to JupyterLab since the earliest stages of JupyterLab's development. This is in line with creating an opt-in set of tools to provide more IDE-like environment for users who want to dive into the code.

## Current status

The emerging standard in this space has been the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/), which we have been adopting in Jupyter projects, cf. @johanmabille's work on https://github.com/jupyter/jupyter_client/issues/446 and the pull requests linked in that issue.

## Next steps

I propose we create a `jupyterlab/debugger` repository for a JupyterLab extension that provides a user interface for debugging tools within JupyterLab.

Full disclosure - I work at Two Sigma and we are interested in this space and working on this functionality in the coming months.

**Comment by SylvainCorlay** [comment]
+1 on this.

**Comment by JohanMabille** [comment]
I have added back the debug messages in https://github.com/jupyterlab/jupyterlab/pull/6704. Even if this PR should not been merged before the protocol is updated, the branch can be used to test the JupyterLab extension providing a user interface for debugging.
