### ISSUE TITLE
JupyterLab Meeting 10 June #ShutdownSTEM

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#68]
I propose we follow the lead of [Pangeo](https://discourse.pangeo.io/t/shutdownstem-and-strike4blacklives-on-wednesday-june-10/638) and others in observing [#ShutDownSTEM](https://www.shutdownstem.com/) in lieu of the standard meeting.  The meeting time would be dedicated to discussion about how we as a community can help eradicate systemic racism.

**Comment by saulshanabrook** [comment]
Thanks Steve, for bringing this up. I support this proposal.

**Comment by SylvainCorlay** [comment]
As much as I was actually going to connect tomorrow, and I would love to see you all, I 100% support this.

**Comment by tgeorgeux** [comment]
I think we could make it a productive use of time for a discussion. The wording of the goal here of "help eradicate systemic racism" is a bit lofty. I think "taking stock of where we are at, and what our next steps could be" a less idealistic goal. 

I don't mean to be pedantic, but it feels like a bit of hubris to suggest something so extreme.

I'll spend some time today putting some topics in [the agenda](https://hackmd.io/Uscrk0N1RhCtX-p6ZHUuWQ?both#8-January-2020-Weekly-Meeting) we could discuss tomorrow, I would appreciate it if others would be willing to do the same.

**Comment by blink1073** [comment]
I was echoing the original language of the #ShutDownSTEM website.  I agree that we should have an agenda, but I don't think we should sell short the overarching goal.

**Comment by jasongrout** [comment]
+1 to using our discussion time for this.

**Comment by blink1073** [comment]
Thanks @tgeorgeux for kicking that off.  Unfortunately I have a medical appointment tomorrow during the meeting time but I added some further ideas in the notes.

**Comment by jasongrout** [comment]
Every three weeks, I have a conflict with the JupyterCon organization meeting, and unfortunately that's tomorrow, so I won't be there at the meeting tomorrow either :(. I'd love to discuss these things another time tomorrow or this week (or another time if that's not good).

**Comment by telamonian** [comment]
I'm open to rescheduling in order to include as many members of core as possible. Presumably we're the ones in a position to effect change here.

Maybe noon est on thurs or fri?

**Comment by jasongrout** [comment]
I could do noon ET Thursday or 11am ET Friday. We have enough people coming to the dev meeting that I don't think we should cancel the dev meeting discussion, though.

**Comment by tgeorgeux** [comment]
I am open to moving it, either of those times will work for me. I see a few options for tomorrow:

1) Have our meeting as a normal meeting tomorrow. 
2) Have our meeting as normal but leave the notes up, ask people to contribute if they are willing.
3) Use the first half of the meeting to discuss @shutdownstem and garner ideas from the community on how to help, then follow on with any issues people have to discuss about JupyterLab.
4) Use tomorrow's meeting as a time to discuss, as planned, then have a follow-on meeting with more members of the core team.

I think there's significance to not going about business as usual, the point of the website was talking about tomorrow specifically and noted, 

Participating in this strike means:
- No research
- No meetings
- No classes
- No business as usual

Thoughts?

**Comment by blink1073** [comment]
Here are the meeting notes from the [Pangeo team](https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit)

**Comment by jasongrout** [comment]
Are we meeting at 9am PT (i.e., right now?).

**Comment by blink1073** [comment]
Following up, there was more discussion at 9am PT this morning, mostly reflecting on the discussions that took place yesterday.  

I suggest we take the next week for independent thought and then if anyone has any further ideas they are welcome to put them here or bring them to next week's meeting or to the Governance call on Tuesday.

**Comment by blink1073** [comment]
Some suggested organizations for donation:

-     ACLU Foundation
-     Black Lives Matter Global Network
-     Brennan Center for Justice
-     Equal Justice Initiative
-     Lawyers' Committee for Civil Rights Under the Law
-     NAACP
-     NAACP Legal Defense and Educational Fund
-     National Bar Institute
-     National Museum of African American History and Culture
-     National Urban League
-     Thurgood Marshall College Fund
-     UNCF (United Negro College Fund)
-     Year Up

**Comment by blink1073** [comment]
Suggested listening material: https://www.sceneonradio.org/seeing-white/

**Comment by blink1073** [comment]
Suggested mini-conference this week in honor of Juneteenth: https://www.juneteenthconf.com/

**Comment by blink1073** [comment]
I wrote a blog post with my thoughts after listening to Seeing White: https://medium.com/@steven.silvester/beyond-not-racist-4e1ea8b62b51

**Comment by blink1073** [comment]
Thanks all for helping to make this possible.  Keep the momentum!
