### ISSUE TITLE
17 June 2020 JupyterLab Weekly Team Meeting

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/team-compass#70]
### 17 June 2020 Weekly Meeting
- Mehmet: present Galata (JupyterLab UI Testing Framework)
- Eric
    - JupyterLab Server as Server Extension [jupyterlab/79](https://github.com/jupyterlab/jupyterlab_server/pull/79) and [jupyterlab-server/7416](https://github.com/jupyterlab/jupyterlab/pull/7416) updated and green - Depends on a few jupyter_server PR/issues ([Confusion between extension_name and module name](https://github.com/jupyter/jupyter_server/issues/222), [Existing Classical Server Extension Support](https://github.com/jupyter/jupyter_server/issues/243)...)
    - [Race Condition with Slow Restarting Kernels](https://github.com/jupyterlab/jupyterlab/issues/8477): Opened PR [jupyterlab/8562](https://github.com/jupyterlab/jupyterlab/pull/8562) which adds `terminating` state in the Kernel Status Indicator (with new method on `ISessionContext`) and blocks cell run if Kernel is terminating - Will update PR with cell run queuing with toast in a second iteration.

- Saul
    - Future of [JupyterLab Vim](https://github.com/jwkvam/jupyterlab-vim)
        - JupyterLab already has Vim key bindings for text editing, this extends it to allow command mode in the notebook
        - Huge number of stars and users!
        - Current version unmaintained, fork is updated for most recent jlab https://github.com/axelfahy/jupyterlab-vim
        - We have a client who uses this
        - Currently uses some hacks: https://github.com/axelfahy/jupyterlab-vim/blob/c4e43f940ef4be4c961608b6192412d2f3a33d1f/src/index.ts#L61
        - Going to look into either bringing into core or adding hooks in core to make less hacky
        - Any thoughts from others on whether I should explore moving this into core?
        - Conclusions:
            - We don't wanna move this into core
            - There is support for making it less hacky, by exposing ways to override codemirror more easily
- Athan
    - JupyterLab ToC context menus: https://github.com/jupyterlab/jupyterlab-toc/pull/141
- Tim
    - Cal Poly interns started this week. Expect to see them in here from time to time.
        - Snippets UI
        - Tabular Data editor
        - JupyterLab Viola Extension (customizeable dashboards)
- Jason
  - Extension system refactor
- Brian
    - Canceling meetings on Juneteenth 6/19 to reflect on systemic racism and injustice.
    - Aiming to get an improved document oriented UX into JLab for 3.0.
        - https://github.com/jupyterlab/jupyterlab/issues/8567
    - Starting to work on task breakdown for overall RTC work

- Additional Discussion
    - Minor release still feasible?
    - Release timeline for 3.0
    - Priorities for 3.0
    - Triage for 3.0
    - [Dropping python 3.5 and 3.6 support](https://github.com/jupyterlab/jupyterlab/issues/8577)

**Comment by ianhi** [comment]
@saulshanabrook is there anywhere that I can follow any changes related to vim mode in jupyterlab? I'm interested both as a vim bindings user and as a creator of two small extensions that add functionality to vim mode.

**Comment by echarles** [comment]
@ianhi I have opened https://github.com/jupyterlab/jupyterlab/issues/8592 to further discuss the VIM mode in cell editors. Happy to get your feedbacks there.
