### ISSUE TITLE
JupyterCon Sprint Plans

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/team-compass#73]
With [JupyterCon](https://jupytercon.com/participate/#Call%20for%20proposals) announced I was wondering if there was already a plan for the sprints.

![image](https://user-images.githubusercontent.com/3627835/87106937-272b9400-c224-11ea-9e72-8787f61e398b.png)

I would like to help any way I can :-)

**Comment by blink1073** [comment]
The [form](https://docs.google.com/forms/d/e/1FAIpQLScbVsOWFIfMBpgrstfXCURErWpYkySDYX5Ai_drXPo1UENDjQ/viewform) calls for a Sprint Leader and a Maintainer rep.  I'm happy to take the Maintainer rep if you can take the Sprint Leader role @goanpeca.

**Comment by goanpeca** [comment]
Hey @blink1073 sure thing, but maybe we could add this topic to the agenda for the next dev meeting just to gather availability and interests.

**Comment by blink1073** [comment]
Sounds good.  I'm sure @jasongrout and @saulshanabrook will be interested.  (nudge nudge).

**Comment by goanpeca** [comment]
(Say no more, say no more...)

**Comment by jtpio** [comment]
Closing since JupyterCon is now over.

Thanks all!
