### ISSUE TITLE
JupyterLab Pull Requests Extension

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/team-compass#8]
## Background

Pull requests are an important part of the dev workflow. Users currently would use JupyterLab for development and then switch to the respective Git hosting service website (e.g. GitHub) for PRs. GitHub (among others) also does not offer a visual diff experience for `ipynb` files which have to be reviewed in their raw JSON format.

## Current Status

@timnlupo has been working to develop an extension for performing pull requests from within JupyterLab. The functionality that is currently built in includes 

* View pull requests assigned to the user and created by the current user
* View the files that changed in each pull request
* View the diff of a file changed in a PR
    * This includes the cell-level diff if the file is a Notebook file
* Add comments to a file in the PR
    * For Notebook files, this provides cell-level comments and line-level diffs for plaintext files. 

All screenshots can be found [here](https://drive.google.com/drive/folders/12UmxhkE26fCKTyj-MYtqNH1RiXLHO2qc) and a GIF at the bottom.

This is backed by a server extension which provides authenticated access to the GitHub APIs and uses the APIs for comment storage and retrieval.

### Relation with other projects

* **Comments**: It is expected that this adopts the commenting system and data model being built in [here](https://github.com/jupyterlab/jupyterlab-commenting). There’s some flexibility that would be required around identity providers and comment storage locations but we should go for a unified commenting experience.
* **Git/NBDime**: This builds upon the work that that has been done in NBDime for Notebook diffs as well as in the [Git extension](https://github.com/jupyterlab/jupyterlab-git) for visual diffs of notebook files to add a layer of commenting on top of diffs.   
    * Pull Requests could be a natural extension to the Git experience. For example, a useful feature would be to create a PR from within JupyterLab after a push from the Git extension
* **GitHub**: [The GitHub extension](https://github.com/jupyterlab/jupyterlab-github)  allows growing GitHub repos, and a possible integration would be to be able to view open PRs on the current repo.

### Feature plans

There’s a few features that would add a ton of value. 

* Check-out a pull request locally - Allowing a user to execute the Notebooks and other files to give a thorough review
* Supporting multiple Git hosting services (BitBucket, GitLab etc). Since folks often do PRs across multiple services, the ability to switch between them within the same extension would be handy
  * In the current implementation, the server extension has a "manager" interface for the Git hosting service which can be implemented  to support another Git hosting service with the same front-end code and handlers.

## Next Steps

We are looking for feedback around the functionality built so far and that planned forward. Our proposal would be to have a `jupyterlab/pull-requests` repo for the extension where this can be iterated upon and contributed to, for building further functionality and integrations with the commenting/nbdime/git.

![JupyterLabPullRequestDemo](https://user-images.githubusercontent.com/43826141/61680621-2c17d080-acbf-11e9-876b-af797e2b09f9.gif)

**Comment by blink1073** [comment]
Thanks for his work @jaipreet-s  and @timnlupo.  I agree with `jupyterlab/pull-requests` and would like to have this installed in @ian-r-rose's [bot](https://github.com/ian-r-rose/jupyterlab-dev-mode-bot) so that we could use this on any PR.

**Comment by blink1073** [comment]
Bot [example](https://github.com/jupyterlab/jupyterlab/pull/6879#issuecomment-514476115)

**Comment by ian-r-rose** [comment]
@blink1073 How would you envision linking to the bot working? @jhamman has also put a bit of work recently into making it more configurable so it would work for other repos.

**Comment by blink1073** [comment]
I think im the build script for the docker image we'd install this extension, which could be replicated elsewhere.

**Comment by jaipreet-s** [comment]
@blink1073 : Thanks! We were also thinking if we could point JupyterLab to a URL (like `/lab/prs?service=github&id=123`) to open up Lab with the given PR view and make the GitHub <-> JupyterLab round-tripping smoother.


Its my first time going through this process and was looking for guidance on next steps here. Do we wait for more feedback before requesting the `jupyterlab/pull-requests` repo?

**Comment by blink1073** [comment]
Done - https://github.com/jupyterlab/pull-requests. Please let me know if you do not have admin rights there.

**Comment by jaipreet-s** [comment]
Awesome, @blink1073! I'm out the rest of this week but we'll move over @timnlupo's code here and draft out a roadmap with next steps.

**Comment by blink1073** [comment]
👍🏼

**Comment by jaipreet-s** [comment]
@blink1073 : I tried to push an initial commit to the repo so @timnlupo can fork it (Apparently we can't fork an empty repo) but I got a permissions error

```
remote: Permission to jupyterlab/pull-requests.git denied to jaipreet-s.
fatal: unable to access 'https://github.com/jupyterlab/pull-requests/': The requested URL returned error: 403
```

**Comment by blink1073** [comment]
@jaipreet-s, it looks like the default when creating a new repo is that no one has write access outside of admins.  I added the "committers" team to that repo.  Cheers!

**Comment by jaipreet-s** [comment]
@blink1073 , I've been trying to push an initial README.md to master but to no avail. So far I've tried

* SSH
```
git push
ERROR: Permission to jupyterlab/pull-requests.git denied to jaipreet-s.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

* HTTPS

```
Username for 'https://github.com/jupyterlab/pull-requests': jaipreet-s
Password for 'https://jaipreet-s@github.com/jupyterlab/pull-requests': 
remote: Permission to jupyterlab/pull-requests.git denied to jaipreet-s.
fatal: unable to access 'https://github.com/jupyterlab/pull-requests/': The requested URL returned error: 403
```

I'm not sure if some permission is still missing or GitHub is messing up because its an empty repo. Both of these credentials (SSH Key and PAT for HTTPS work) for directly pushing to the `jupyterlab-git` repo where I do have permissions)

**Comment by blink1073** [comment]
@jaipreet-s, my mistake, you had admin rights only on the jupyterlab-git repo, I've added you to the committers group.

**Comment by jaipreet-s** [comment]
@blink1073 : Works now! https://github.com/jupyterlab/pull-requests/commit/563bf5dae622d8369c7a5a9eda480aa847154b62.

Good to close this now and move further activity to the repo. Thanks!
