### ISSUE TITLE
Monday 8/3 7:30am PT - Single Doc Mode Review/Demo

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/team-compass#81]
Tomorrow morning (8/3) 7:30 - 8:30 am PT.

For those interested in the improved single document mode upcoming in JupyterLab 3.0, we will have a code review and demo at 7:30 am on the Jupyter Zoom channel (https://calpoly.zoom.us/my/jovyan).

We will be reviewing this PR:

https://github.com/jupyterlab/jupyterlab/pull/8715

This is a significant change to the JupyterLab UX and URL handling and it backwards incompatible so we are trying to get as many people to have a look at this as possible.

**Comment by echarles** [comment]
https://github.com/jupyterlab/jupyterlab_server/pull/101 has been merged in jupyterlab_server master and removes `treeUrl`, `workspaceUrl`... Does jlab master still works with latest jlab_server?

**Comment by echarles** [comment]
Asking that because after merging the branches for jlab on jserver (https://github.com/jupyterlab/jupyterlab_server/pull/79 and https://github.com/jupyterlab/jupyterlab/pull/7416), tests are failing on my end on the jupyter_server jlab ci due to missing workspace_url...
