### ISSUE TITLE
Localization: Move goanpeca/jupyterlab-language-packs to jlab org.

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/team-compass#87]
For the localization work, to be able to distribute the translations, https://github.com/goanpeca/jupyterlab-language-packs and https://github.com/goanpeca/jupyterlab-language-pack-cookiecutter were created.

Currently, https://github.com/goanpeca/jupyterlab-language-packs is the repository linked to the Crowdin work. On this repository the translations for both core and 3rd party extensions (living on the JLab org or else) live.

I still need to do some cleanup and write some docs.

**Comment by blink1073** [comment]
I approve of moving both of these repositories to the JupyterLab org.

**Comment by afshin** [comment]
💯 👍 🔥
🚀:shipit:🎉

**Comment by goanpeca** [comment]
I already added @blink1073 , @afshin  and @saulshanabrook as collaborators on all the repos. Any other step I should take on my side?

Thanks!

**Comment by jasongrout** [comment]
I think to transfer a repo you have to be an owner in both orgs. The way we typically do this is make you temporarily an owner in the jlab org while you transfer the repo over. It's probably best to do this in a live video call.

**Comment by goanpeca** [comment]
@jasongrout let me know when we can do this. Thanks!

**Comment by jasongrout** [comment]
@goanpeca - please ping me on gitter when it is a good time for you.

**Comment by goanpeca** [comment]
This has been migrated. Thanks!

Closing
